from nautobot.apps.jobs import Job, register_jobs
from nautobot.dcim.models import Device

HTML_STYLE = """
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #1F4E79; }
  h1 { background: #1F4E79; color: white; padding: 16px; border-radius: 6px; }
  h3 { color: #2E75B6; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
  th { background: #1F4E79; color: white; padding: 10px; text-align: left; }
  td { padding: 9px 10px; border-bottom: 1px solid #AABBD4; }
  tr:nth-child(even) { background: #EBF3FB; }
  .summary { background: #E2EFDA; border-left: 5px solid #375623;
             padding: 12px 16px; margin-top: 24px; border-radius: 4px; }
  .footer { margin-top: 40px; font-size: 12px; color: #595959; text-align: center; }
</style>
"""

class ActiveDeviceReport(Job):
    class Meta:
        name = "1. Device Inventory Report"
        description = "Generates a PDF-ready HTML report of all active devices by location"
        has_sensitive_variables = False

    def run(self):
        devices = Device.objects.filter(status__name="Active").order_by("location__name", "name")
        if not devices.exists():
            self.logger.warning("No active devices found!")
            return

        rows = ""
        for device in devices:
            location = device.location.name if device.location else "—"
            role = device.role.name if device.role else "—"
            platform = device.platform.name if device.platform else "—"
            ip = device.primary_ip.address if device.primary_ip else "—"
            status = device.status.name if device.status else "—"
            rows += f"""
            <tr>
              <td>{device.name}</td>
              <td>{location}</td>
              <td>{role}</td>
              <td>{platform}</td>
              <td>{ip}</td>
              <td>{status}</td>
            </tr>"""

        html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Device Inventory Report</title>
{HTML_STYLE}</head><body>
<h1>📋 Device Inventory Report — Link3 Technologies Ltd.</h1>
<p>Generated by Nautobot | Total Active Devices: <strong>{devices.count()}</strong></p>
<table>
  <thead><tr>
    <th>Device Name</th><th>Location</th><th>Role</th>
    <th>Platform</th><th>Primary IP</th><th>Status</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table>
<div class="summary">
  <strong>Summary:</strong> Total active devices: {devices.count()}
</div>
<div class="footer">Link3 Technologies Ltd. — Technology Department | Nautobot v3.0.6</div>
</body></html>"""

        self.create_file("device_inventory_report.html", html)
        self.logger.info(f"Report generated! {devices.count()} active devices found. Download the file above.")


register_jobs(ActiveDeviceReport)
