from nautobot.apps.jobs import Job, register_jobs
from nautobot.dcim.models import Device
from nautobot.ipam.models import Prefix
from nautobot.circuits.models import Circuit
import json


class GraphDashboardReport(Job):
    class Meta:
        name = "5. Graph Dashboard Report"
        description = "Interactive charts — Devices, IPs, Circuits, BTS breakdown"
        has_sensitive_variables = False

    def run(self):
        # 1. Devices by Role
        role_data = {}
        for device in Device.objects.filter(status__name="Active"):
            role = device.role.name if device.role else "Unknown"
            role_data[role] = role_data.get(role, 0) + 1

        # 2. Devices by Location (top 10)
        location_data = {}
        for device in Device.objects.filter(status__name="Active"):
            loc = device.location.name if device.location else "Unknown"
            location_data[loc] = location_data.get(loc, 0) + 1
        top_locations = dict(
            sorted(location_data.items(), key=lambda x: x[1], reverse=True)[:10]
        )

        # 3. Circuit Status
        circuit_data = {}
        for circuit in Circuit.objects.all():
            status = circuit.status.name if circuit.status else "Unknown"
            circuit_data[status] = circuit_data.get(status, 0) + 1

        # 4. IP Utilization Buckets — fixed for v3 tuple return
        low = medium = high = critical = 0
        for prefix in Prefix.objects.all():
            try:
                util_raw = prefix.get_utilization()
                if isinstance(util_raw, tuple):
                    used, total = util_raw
                    pct = (used / total * 100) if total else 0.0
                else:
                    pct = float(util_raw) * 100
            except Exception:
                pct = 0.0

            if pct < 25:
                low += 1
            elif pct < 50:
                medium += 1
            elif pct < 80:
                high += 1
            else:
                critical += 1

        # 5. BTS Active vs Inactive
        bts_devices = Device.objects.filter(name__icontains="BTS")
        bts_active = bts_devices.filter(status__name="Active").count()
        bts_inactive = bts_devices.exclude(status__name="Active").count()

        # 6. Devices by Status
        status_data = {}
        for device in Device.objects.all():
            s = device.status.name if device.status else "Unknown"
            status_data[s] = status_data.get(s, 0) + 1

        # KPI totals
        total_devices = Device.objects.count()
        total_circuits = Circuit.objects.count()
        total_prefixes = Prefix.objects.count()
        total_bts = bts_active + bts_inactive

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Link3 Network Dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: Arial, sans-serif; background: #F0F4F8; color: #1F4E79; }}
  .header {{ background: #1F4E79; color: white; padding: 24px 40px; }}
  .header h1 {{ font-size: 26px; }}
  .header p {{ font-size: 14px; opacity: 0.8; margin-top: 4px; }}
  .kpi-row {{ display: flex; gap: 16px; padding: 24px 40px 0; }}
  .kpi {{ background: white; border-radius: 8px; padding: 20px 24px;
          flex: 1; box-shadow: 0 2px 8px rgba(0,0,0,0.08);
          border-top: 4px solid #2E75B6; text-align: center; }}
  .kpi h2 {{ font-size: 40px; color: #1F4E79; }}
  .kpi p {{ font-size: 13px; color: #595959; margin-top: 4px; }}
  .charts {{ display: grid; grid-template-columns: 1fr 1fr;
             gap: 24px; padding: 24px 40px; }}
  .chart-box {{ background: white; border-radius: 8px; padding: 24px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.08); }}
  .chart-box h3 {{ font-size: 15px; color: #1F4E79; margin-bottom: 16px;
                   border-bottom: 2px solid #EBF3FB; padding-bottom: 8px; }}
  .chart-wide {{ grid-column: span 2; }}
  .footer {{ text-align: center; padding: 24px;
             font-size: 12px; color: #595959; }}
</style>
</head>
<body>

<div class="header">
  <h1>📊 Link3 Network Dashboard</h1>
  <p>Technology Department — Generated by Nautobot v3.0.6</p>
</div>

<div class="kpi-row">
  <div class="kpi"><h2>{total_devices}</h2><p>Total Devices</p></div>
  <div class="kpi"><h2>{total_circuits}</h2><p>Total Circuits</p></div>
  <div class="kpi"><h2>{total_prefixes}</h2><p>IP Prefixes</p></div>
  <div class="kpi"><h2>{total_bts}</h2><p>BTS Devices</p></div>
</div>

<div class="charts">
  <div class="chart-box">
    <h3>🖥️ Active Devices by Role</h3>
    <canvas id="roleChart"></canvas>
  </div>
  <div class="chart-box">
    <h3>🔌 Circuit Status Breakdown</h3>
    <canvas id="circuitChart"></canvas>
  </div>
  <div class="chart-box chart-wide">
    <h3>📍 Top 10 Locations by Device Count</h3>
    <canvas id="locationChart"></canvas>
  </div>
  <div class="chart-box">
    <h3>🌐 IP Prefix Utilization Buckets</h3>
    <canvas id="ipChart"></canvas>
  </div>
  <div class="chart-box">
    <h3>📡 BTS Health Overview</h3>
    <canvas id="btsChart"></canvas>
  </div>
  <div class="chart-box chart-wide">
    <h3>📋 All Devices by Status</h3>
    <canvas id="statusChart"></canvas>
  </div>
</div>

<div class="footer">
  Link3 Technologies Ltd. — Technology Department | Confidential
</div>

<script>
const COLORS = ['#1F4E79','#2E75B6','#00B0F0','#375623','#843C0C',
                '#70AD47','#ED7D31','#FFC000','#4472C4','#FF0000'];

new Chart(document.getElementById('roleChart'), {{
  type: 'doughnut',
  data: {{
    labels: {json.dumps(list(role_data.keys()))},
    datasets: [{{ data: {json.dumps(list(role_data.values()))},
      backgroundColor: COLORS }}]
  }},
  options: {{ plugins: {{ legend: {{ position: 'right' }} }} }}
}});

new Chart(document.getElementById('circuitChart'), {{
  type: 'pie',
  data: {{
    labels: {json.dumps(list(circuit_data.keys()))},
    datasets: [{{ data: {json.dumps(list(circuit_data.values()))},
      backgroundColor: COLORS }}]
  }},
  options: {{ plugins: {{ legend: {{ position: 'right' }} }} }}
}});

new Chart(document.getElementById('locationChart'), {{
  type: 'bar',
  data: {{
    labels: {json.dumps(list(top_locations.keys()))},
    datasets: [{{
      label: 'Device Count',
      data: {json.dumps(list(top_locations.values()))},
      backgroundColor: '#2E75B6'
    }}]
  }},
  options: {{
    plugins: {{ legend: {{ display: false }} }},
    scales: {{ y: {{ beginAtZero: true }} }}
  }}
}});

new Chart(document.getElementById('ipChart'), {{
  type: 'bar',
  data: {{
    labels: ['Low (0-24%)', 'Medium (25-49%)', 'High (50-79%)', 'Critical (80%+)'],
    datasets: [{{
      label: 'Prefixes',
      data: [{low}, {medium}, {high}, {critical}],
      backgroundColor: ['#70AD47','#FFC000','#ED7D31','#FF0000']
    }}]
  }},
  options: {{
    plugins: {{ legend: {{ display: false }} }},
    scales: {{ y: {{ beginAtZero: true }} }}
  }}
}});

new Chart(document.getElementById('btsChart'), {{
  type: 'doughnut',
  data: {{
    labels: ['Active', 'Inactive'],
    datasets: [{{
      data: [{bts_active}, {bts_inactive}],
      backgroundColor: ['#375623','#843C0C']
    }}]
  }},
  options: {{ plugins: {{ legend: {{ position: 'right' }} }} }}
}});

new Chart(document.getElementById('statusChart'), {{
  type: 'bar',
  data: {{
    labels: {json.dumps(list(status_data.keys()))},
    datasets: [{{
      label: 'Devices',
      data: {json.dumps(list(status_data.values()))},
      backgroundColor: '#1F4E79'
    }}]
  }},
  options: {{
    plugins: {{ legend: {{ display: false }} }},
    scales: {{ y: {{ beginAtZero: true }} }}
  }}
}});
</script>
</body></html>"""

        self.create_file("link3_network_dashboard.html", html)
        self.logger.info(
            f"Dashboard generated! {total_devices} devices, "
            f"{total_circuits} circuits, {total_prefixes} prefixes. "
            "Download and open in Chrome."
        )


register_jobs(GraphDashboardReport)
